"""
Delux Radio — SQLAlchemy Database Models (SQLite)
"""
from sqlalchemy import (
    create_engine, Column, Integer, String, Boolean,
    DateTime, Text, ForeignKey, Float
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime

DATABASE_URL = "sqlite:///./delux_radio.db"

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_tables():
    Base.metadata.create_all(bind=engine)
    print("[OK] Database tables created.")


# ─── Models ───────────────────────────────────────────────────────────────────

class Song(Base):
    __tablename__ = "songs"

    id             = Column(Integer, primary_key=True, index=True)
    title          = Column(String(255), nullable=False)
    artist         = Column(String(255), nullable=False)
    movie          = Column(String(255), nullable=True)
    release_year   = Column(Integer, nullable=False)
    language       = Column(String(50), default="Hindi")
    youtube_video_id = Column(String(50), nullable=False)
    duration       = Column(Integer, default=240)  # seconds
    active         = Column(Boolean, default=True)
    created_at     = Column(DateTime, default=datetime.utcnow)

    requests = relationship("Request", back_populates="song")


class User(Base):
    __tablename__ = "users"

    id           = Column(Integer, primary_key=True, index=True)
    display_name = Column(String(100), nullable=False)
    session_id   = Column(String(100), unique=True, nullable=False)
    is_banned    = Column(Boolean, default=False)
    created_at   = Column(DateTime, default=datetime.utcnow)
    last_seen    = Column(DateTime, default=datetime.utcnow)


class Request(Base):
    __tablename__ = "requests"

    id                = Column(Integer, primary_key=True, index=True)
    song_id           = Column(Integer, ForeignKey("songs.id"), nullable=True)
    song_name_raw     = Column(String(255), nullable=False)   # what user typed
    requester_name    = Column(String(100), nullable=False)
    dedicated_to      = Column(String(100), nullable=True)
    story             = Column(Text, nullable=True)
    emotion_tag       = Column(String(50), nullable=True)      # romantic, nostalgic, etc.
    rj_script         = Column(Text, nullable=True)            # generated by Llama 3
    rj_audio_path     = Column(String(500), nullable=True)     # mixed audio file
    status            = Column(String(50), default="pending")  # pending→queued→announcing→playing→completed
    moderation_status = Column(String(20), default="pending")  # pending→approved→rejected
    queue_position    = Column(Integer, nullable=True)
    created_at        = Column(DateTime, default=datetime.utcnow)
    processed_at      = Column(DateTime, nullable=True)

    song = relationship("Song", back_populates="requests")


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id                = Column(Integer, primary_key=True, index=True)
    session_id        = Column(String(100), nullable=False)
    display_name      = Column(String(100), nullable=False)
    message           = Column(Text, nullable=False)
    moderation_status = Column(String(20), default="approved")
    created_at        = Column(DateTime, default=datetime.utcnow)


class RadioState(Base):
    __tablename__ = "radio_state"

    id               = Column(Integer, primary_key=True, default=1)
    current_song_id  = Column(Integer, ForeignKey("songs.id"), nullable=True)
    youtube_video_id = Column(String(50), nullable=True)
    started_at       = Column(DateTime, nullable=True)
    mode             = Column(String(20), default="auto")   # auto | request
    is_paused        = Column(Boolean, default=False)


class RJAnnouncement(Base):
    __tablename__ = "rj_announcements"

    id             = Column(Integer, primary_key=True, index=True)
    request_id     = Column(Integer, ForeignKey("requests.id"), nullable=False)
    script         = Column(Text, nullable=False)
    voice_audio_path = Column(String(500), nullable=True)
    duration       = Column(Float, nullable=True)
    status         = Column(String(20), default="pending")   # pending|generating|ready|played
    created_at     = Column(DateTime, default=datetime.utcnow)


class AdminUser(Base):
    __tablename__ = "admin_users"

    id           = Column(Integer, primary_key=True, index=True)
    username     = Column(String(100), unique=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    created_at   = Column(DateTime, default=datetime.utcnow)
